### ISSUE TITLE
nether is invisible?

### ISSUE THREAD

**Issue by switchuwu** [MCRcortex/nvidium#33] opened 2023-06-05 14:32 UTC
![2023-06-05_16 29 54](https://github.com/MCRcortex/nvidium/assets/59403996/79d9cb74-1994-47ea-aa89-28582b2e26c1)

only happens when nvidium is enabled

[log.txt](https://github.com/MCRcortex/nvidium/files/11653618/log.txt)

**Comment by switchuwu** [comment] 2023-06-05 14:36
no its not because of other mods. also happens when only sodium and nvidium is enabled
[log.txt](https://github.com/MCRcortex/nvidium/files/11653648/log.txt)

**Comment by ruvaldak** [comment] 2023-06-06 03:37
try using fabric instead of quilt. works fine for me, even with a lot of mods & resource packs on 1.19.4.
![image](https://github.com/MCRcortex/nvidium/assets/15901769/5b946262-5c33-434a-9dcc-41c65528e419)

**Comment by eConnah** [comment] 2023-06-15 11:40
I also have this issue; When setting region keep distance to 120 or above all nearby chunks become invisible, lowering it makes nearby chunks visible again but doesn't save chunks when they exit my render distance. Setting it to 'keep all' makes everything invisible. This only happens in the nether not the overworld or the end.
![119](https://github.com/MCRcortex/nvidium/assets/63052937/e8b523a1-d757-473e-9898-fe5df0bdaa9e)
![120](https://github.com/MCRcortex/nvidium/assets/63052937/c1d01615-3104-48e7-8b2c-8a9dbbb8f3f7)
![keep-all](https://github.com/MCRcortex/nvidium/assets/63052937/e069e15a-6f16-412c-9ed7-d48143051048)
[latest.log](https://github.com/MCRcortex/nvidium/files/11757010/latest.log)

**Comment by MCRcortex** [comment] 2023-06-15 12:49
the cause of this issue is unknown but confirmed, unsure how to fix it

**Comment by MCRcortex** [comment] 2023-06-23 11:06
Fixed in 0.1.12

**Closed as completed by MCRcortex** 2023-06-23 11:06 UTC
Labels: bug
