### ISSUE TITLE
Rendering issue with additive modpack

### ISSUE THREAD

**Issue by LIXFERSI** [MCRcortex/nvidium#76] opened 2023-09-11 22:45 UTC
Without nvidium
![2023-09-11_23 41 43](https://github.com/MCRcortex/nvidium/assets/132794058/45bb2ad2-b4be-42c4-b23a-99a312fe0e2d)
With nvidium
![2023-09-11_23 43 08](https://github.com/MCRcortex/nvidium/assets/132794058/6452312e-2249-4371-93e7-a6c5195870db)
I updated all the mods from the modpack, then added nvidium

Fabric 1.20.1
https://modrinth.com/modpack/additive

**Comment by alvesvaren** [comment] 2023-09-12 09:05
Possible duplicate of #55

**Comment by MCRcortex** [comment] 2024-01-08 06:28
As of nvidium 0.2.3-beta, there is translucency sorting and this should no longer be an issue

**Closed as completed by MCRcortex** 2024-01-08 06:28 UTC
