### ISSUE TITLE
render issues with water and fog

### ISSUE THREAD

**Issue by tomingrad** [MCRcortex/nvidium#70] opened 2023-08-18 20:49 UTC
here are screenshots - https://imgur.com/a/xZoCc4d
first is without nvidium and second is with the mod

(dont know why it shows, it is an adult image lol)

**Comment by lilnarco** [comment] 2023-09-24 17:02
The fog issue is my only complaint with the current build as well. It seems to limit the major reason I'd use this mod... having a large render distance.

**Comment by Synnef-8826** [comment] 2023-10-13 08:38
Feel like it's worth bumping this. The black "fog" in the distance gets pretty bad in the nether, where the vanilla fog is thicker by design... Render distance is 16.
Nvidium's settings are at default except I increased GPU memory by 1GB (the issue still appeared at the default 2GB).

The water thing is probably just on your end though, I've never had that in my game. Maybe outdated (or too new?) drivers, if it's not an Nvidium problem with your GPU itself? The only thing I'm certain is not the problem are other mods, seeing as I'm not the only one getting this.

Just an example of how bad it gets... `0.2.0-beta` of course.
![2023-10-13_08 51 13](https://github.com/MCRcortex/nvidium/assets/106876032/cc58ae79-ce25-4159-be97-b3fa8602c459)

**Comment by MCRcortex** [comment] 2023-10-13 23:54
what other mods are you using?

**Comment by Synnef-8826** [comment] 2023-10-14 08:47
I just checked on a fresh instance with Nvidium, Sodium and Sodium Extra (to disable fog), and the issue still persists (see below). Either way. here's my complete list in case there happens to be another conflict.
![](https://github.com/MCRcortex/nvidium/assets/106876032/f48f162b-2c90-4373-8b9a-f14c29a07723)

Funnily enough, it seems like the blacked out terrain seems to be the one that is normally hidden by fog. That explains my previous comment quite well I think, since I mentioned how the nether's fog is intentionally thicker than the overworld's.
![](https://github.com/MCRcortex/nvidium/assets/106876032/5f57f50f-f0c4-4ddb-b63f-2d2f6958b8d7)
*Fog re-enabled in Sodium Extra, for the comparison. Notice how there's no black terrain anymore, and it's hidden away instead. The behavior is the same without Sodium Extra to disable fog. Also, the ice looks a bit weird :D*
![](https://github.com/MCRcortex/nvidium/assets/106876032/becca016-6860-4395-acd6-c2ec54cfeb2f)

The first conclusion I can draw is it *is* a mod problem, because Nvidium is expecting fog to be present...? Or maybe it's just an incompatibility with Sodium Extra itself, but I haven't tested with other fog removing mods.

**Comment by MCRcortex** [comment] 2023-10-14 08:48
Ah im not sure how sodium extra's fog disable works, i think that would explain it

**Comment by Synnef-8826** [comment] 2023-10-14 09:25
Definitely, [this mod](https://modrinth.com/mod/bactromod) seems to cause no problems with the "Disable Terrain Fog" option, and Disable Thick Fog for the nether, so it should serve as a temporary replacement. It requires the Kotlin mod for Fabric (and Mod Menu to configure like everything) though.

I guess I'll go raise the issue on the Sodium Extra page, as it's pretty much the go-to option for no fog (and what most Nvidium users use as well, probably), thanks for all the help!

**Comment by MCRcortex** [comment] 2024-01-08 06:33
Fog should be fixed as of nvidium 0.2.1

**Closed as completed by MCRcortex** 2024-01-08 06:33 UTC
