### ISSUE TITLE
Chunks are visible on ice 0.2 Beta

### ISSUE THREAD

**Issue by Redtendo22** [MCRcortex/nvidium#82] opened 2023-09-25 19:16 UTC
![2023-09-25_21 13 53](https://github.com/MCRcortex/nvidium/assets/116605206/95f2dfe4-fe6a-474e-b669-65bbe3cff6f1)

**Comment by MikiP98** [comment] 2023-10-30 14:53
This is a duplicate of #9

**Comment by PFnove** [comment] 2023-11-01 14:32
you need to set "Translucency Sorting" to Sections or Quads

**Closed as completed** 2024-01-08 06:26 UTC
