### ISSUE TITLE
What version of soudium is compatible with sodium 1.20.1-0.5.10 or vice versa

### ISSUE THREAD

**Issue by lucarnival** [MCRcortex/nvidium#206] opened 2024-06-25 08:51 UTC
What version is compatible with another?
Anyone knows or perhaps havent updated their sodium so we know what to use?

**Comment by KarmaMarazu** [comment] 2024-06-25 08:53
please next time before you make an issue read other ones if it hasnt been posted before literally the 2 before this have the answe #204 tells you all you need and #205 is a duplicate of this

**Comment by MrCatlio** [comment] 2024-06-25 12:19
> What version is compatible with another?
> Anyone knows or perhaps havent updated their sodium so we know what to use?

Theses are known to work currently for 1.20.1
Sodium: 0.5.7
Sodium Extras: 0.5.4
Nvidium: 0.2.6

**Closed as completed** 2024-07-14 11:24 UTC
