### ISSUE TITLE
Update to Sodium 0.6.0

### ISSUE THREAD

**Issue by tofo2** [MCRcortex/nvidium#265] opened 2024-11-26 14:55 UTC
Please Update Nvidium to Sodium 0.6.0 it isnt in beta state anymore.

**Comment by KarmaMarazu** [comment] 2024-11-26 14:59
duplicate of #241 cortex is currently very busy and doesnt have time will be updated once she has time and energy to do so

**Closed as completed by KarmaMarazu** 2024-11-26 14:59 UTC
